### ISSUE TITLE
gfapi access fails with device size of 0

### ISSUE THREAD

**Issue by pcuzner** [agrover/tcmu-runner#49]
I have a backing file on gluster of 8g. This file is accessed fine through the regular fileio path, but when I attempt to use gfapi the device is not correctly detected (unsupported sector size) and therefore not added to the client.

Two files attached - one shows the attach when using fileio, and the other illustrates the issue when trying to use gfapi.
[add_fileio.txt](https://github.com/agrover/tcmu-runner/files/192502/add_fileio.txt)
[add_gfapi.txt](https://github.com/agrover/tcmu-runner/files/192503/add_gfapi.txt)

**Comment by pcuzner** [comment]
Also, when I look at the tcmu-runner service I see i/o errors
[root@iscsi-1 ~]# systemctl status tcmu-runner
● tcmu-runner.service - LIO Userspace-passthrough daemon
   Loaded: loaded (/usr/lib/systemd/system/tcmu-runner.service; static; vendor preset: disabled)
   Active: active (running) since Tue 2016-03-29 09:28:30 NZDT; 1h 6min ago
 Main PID: 2116 (tcmu-runner)
    Tasks: 10 (limit: 512)
   CGroup: /system.slice/tcmu-runner.service
           └─2116 /usr/bin/tcmu-runner

Mar 29 10:05:45 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000950 ffffffff a3 0 0 21037056
Mar 29 10:05:45 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000a90 ffffffff a3 0 0 17956864
Mar 29 10:05:45 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000950 ffffffff a3 0 0 26411008
Mar 29 10:05:45 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000950 ffffffff a3 0 0 21037056
Mar 29 10:16:49 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000950 ffffffff a3 0 0 17956864
Mar 29 10:16:49 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000950 ffffffff a3 0 0 26411008
Mar 29 10:16:49 iscsi-1.storage.lab tcmu-runner[2116]: io error 0x7f875c000950 ffffffff a3 0 0 21037056

This looks like the catch all error in glfs.c within tcmu_glfs_handle_cmd..
i.e.
	if (result != SAM_STAT_GOOD) {
		errp("io error %p %x %x %d %d %llu\n",
		     cdb, result, cmd, ret, length, (unsigned long long)offset);
	}

I've also tried access with and without multipathd active on the client - same result.

**Comment by agrover** [comment]
A3 is MAINTENANCE IN, which does different things but basically none of those are required so us returning not supported is ok.

The more pressing issue is the unsupported sector size message, and I'm looking into that now.

**Comment by mdillury** [comment]
Not sure if its the same issue.  But I'm getting very similar IO errors in tcmu-runner after configuring access to a glusterfs backing file via gfapi. 

[root@dauseq4vggw2 gvol]# cat /etc/fedora-release
Fedora release 25 (Twenty Five)
[root@dauseq4vggw2 gvol]# uname -a
Linux dauseq4vggw2 4.10.10-200.fc25.x86_64 #1 SMP Thu Apr 13 01:11:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@dauseq4vggw2 gvol]# rpm -qa | egrep 'tcmu|targetcli'
libtcmu-1.1.3-1.fc25.x86_64
targetcli-2.1.fb43-2.fc25.noarch
tcmu-runner-1.1.3-1.fc25.x86_64

[root@dauseq4vggw2 gvol]#  systemctl status tcmu-runner
● tcmu-runner.service - LIO Userspace-passthrough daemon
   Loaded: loaded (/usr/lib/systemd/system/tcmu-runner.service; static; vendor preset: disabled)
   Active: active (running) since Tue 2017-04-25 20:36:21 AEST; 7min ago
 Main PID: 1513 (tcmu-runner)
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/tcmu-runner.service
           └─1513 /usr/bin/tcmu-runner

Apr 25 20:42:56 dauseq4vggw2 tcmu-runner[1513]: Error on read ffffffff 1000
Apr 25 20:42:56 dauseq4vggw2 tcmu-runner[1513]: io error 0x7ff5d4000950 2 28 -1 4096 0
Apr 25 20:43:02 dauseq4vggw2 tcmu-runner[1513]: Error on read ffffffff 1000
Apr 25 20:43:02 dauseq4vggw2 tcmu-runner[1513]: io error 0x7ff5d4000950 2 28 -1 4096 0
Apr 25 20:43:08 dauseq4vggw2 tcmu-runner[1513]: Error on read ffffffff 1000
Apr 25 20:43:08 dauseq4vggw2 tcmu-runner[1513]: io error 0x7ff5d4000950 2 28 -1 4096 0
Apr 25 20:43:14 dauseq4vggw2 tcmu-runner[1513]: Error on read ffffffff 1000
Apr 25 20:43:14 dauseq4vggw2 tcmu-runner[1513]: io error 0x7ff5d4000950 2 28 -1 4096 0
Apr 25 20:43:20 dauseq4vggw2 tcmu-runner[1513]: Error on read ffffffff 1000
Apr 25 20:43:20 dauseq4vggw2 tcmu-runner[1513]: io error 0x7ff5d4000950 2 28 -1 4096 0


This is resulting in the iscsi client unable to access the LUNs. 

-- Logs begin at Tue 2017-04-25 09:10:09 UTC. --
Apr 25 10:48:38 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 Add. Sense: Logical unit communication failure
Apr 25 10:48:38 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Apr 25 10:48:38 ip-10-2-0-163 kernel: blk_update_request: I/O error, dev sda, sector 0
Apr 25 10:48:39 ip-10-2-0-163 multipathd[392]: 3600140546fbee0590a74c1ba9bf05780: sda - directio checker reports path is down
Apr 25 10:48:44 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Apr 25 10:48:44 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 Sense Key : Not Ready [current]
Apr 25 10:48:44 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 Add. Sense: Logical unit communication failure
Apr 25 10:48:44 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Apr 25 10:48:44 ip-10-2-0-163 kernel: blk_update_request: I/O error, dev sda, sector 0
Apr 25 10:48:45 ip-10-2-0-163 multipathd[392]: 3600140546fbee0590a74c1ba9bf05780: sda - directio checker reports path is down
Apr 25 10:48:50 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Apr 25 10:48:50 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 Sense Key : Not Ready [current]
Apr 25 10:48:50 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 Add. Sense: Logical unit communication failure
Apr 25 10:48:50 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
Apr 25 10:48:50 ip-10-2-0-163 kernel: blk_update_request: I/O error, dev sda, sector 0
Apr 25 10:48:51 ip-10-2-0-163 multipathd[392]: 3600140546fbee0590a74c1ba9bf05780: sda - directio checker reports path is down
Apr 25 10:48:56 ip-10-2-0-163 kernel: sd 2:0:0:0: [sda] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE

**Comment by mikechristie** [comment]
Adding glfs developer.

@pkalever,  glfs is working ok right?

**Comment by pkalever** [comment]
@mikechristie Yes, It was working fine with me.
At least we have not encountered such problem.

It will be good to know steps to reproduce the issue.
Can we also get "# targetcli ls" output ?

**Comment by mdillury** [comment]
@pkalever I was following the steps as described here: http://blog.gluster.org/2016/04/using-lio-with-gluster/

[root@dauseq4vggw2 ~]# targetcli ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:glfs .............................................................................................. [Storage Objects: 1]
  | | o- glun ................................................................. [gvol@dauseq4vgfs2-eth1/lun.img (10.0GiB) activated]
  | o- user:qcow .............................................................................................. [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.2016-06.com.solnode:gluster:dauseq4vggw2 ...................................................................... [TPGs: 1]
  |   o- tpg1 ............................................................................................... [no-gen-acls, no-auth]
  |     o- acls .......................................................................................................... [ACLs: 1]
  |     | o- iqn.1993-08.org.debian:01:58cc6c30e338 ............................................................... [Mapped LUNs: 1]
  |     |   o- mapped_lun0 ................................................................................... [lun0 user/glun (rw)]
  |     o- luns .......................................................................................................... [LUNs: 1]
  |     | o- lun0 ...................................................................................................... [user/glun]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 192.168.105.62:3260 .............................................................................................. [OK]
  o- loopback ......................................................................................................... [Targets: 0]
  o- vhost ............................................................................................................ [Targets: 0]
